schemaVersion: 2.2.0
metadata:
  name: javafx-dev

components:
  - name: tools
    container:
      image: quay.io/devspaces/ide-java:latest
      memoryLimit: 2Gi
      mountSources: true
      env:
        - name: DISPLAY
          value: ":99"

commands:
  - id: start-xvfb
    exec:
      component: tools
      commandLine: |
        Xvfb :99 -screen 0 1024x768x16 &

  - id: configure-git
    exec:
      component: tools
      commandLine: |
        if [ -n "$GIT_USER_NAME" ]; then git config --global user.name "$GIT_USER_NAME"; fi
        if [ -n "$GIT_USER_EMAIL" ]; then git config --global user.email "$GIT_USER_EMAIL"; fi

  - id: run-javafx
    exec:
      component: tools
      commandLine: "mvn clean javafx:run"
      workingDir: ${PROJECT_SOURCE}
      group:
        kind: run

