schemaVersion: 2.2.0
metadata:
  name: javafx-dev

components:
  - name: tools
    container:
      image: registry.redhat.io/devspaces/udi-rhel9
      memoryLimit: 2Gi
      mountSources: true
      env:
        - name: DISPLAY
          value: ":99"
      command:
        - /bin/bash
        - -c
      args:
        - |
          # Start Xvfb
          Xvfb :99 -screen 0 1024x768x16 &
          # Start the normal UDI entrypoint
          /entrypoint.sh


